dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
addons:
  browserstack:
    username: ${BROWSERSTACK_USERNAME}
    access_key: ${BROWSERSTACK_ACCESS_KEY}
    forcelocal: true

