dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: Eu9IdOCMDNNtwjs0901xE53zsl6ExoZnGTo+8kOEy4qtZj0/PVCHPEfx3Ty9QFm5mSLVW6BVkJB4gHjZPuSKbMYrKIXwSFZcML4xYXMs7oWh2e9ulOVf8iSH/5MPj8+ib+UPcdwkJLhHXm3lIZs+PhySkIFbA045uPXVRT2Xusw=
  - secure: XCtfTIWdmyjp1ZDH9CPs7eXbOTAhfS031GWsru7rlOqPTWy0/RHL3BI5chBnn7Dh6ig34M6jQ2/4hcP/Qy+nPR9Gx44GF0jhEv3oEF5fyeSu3DsanKew3K0CIbnNRC4lEr/4qMaDkN4yLFeYCYpuvr0v2pyGpP9e+k7j3oqOmM8=
  - secure: o1E51adkfzse6ayaKkf+YPi4xMxDvj6ez1oEsI5HljhVuMbgvOYkrs3dkOSfsORBAR+a9F8bSbrOcXyBDzloj3v1G47r4LaSWFk8QTBDvn8cpAzbx1eErT6FcdzxqmeZ22xWXQhEg17mfomCvULc+ueDToXEP1GGkozp7KZyldk=
  - secure: VuUlF+SdWvjKA0jDLJWcHwaL+H/4shfLhy/1C3HulJVuAOtz7+UQvOsbo2s8tXQic25IynvnBxb366wbDHS4yPEi71oTH/KniV3rYa9jsDM/vIUsHi8X09Scwk8CyD84F7aEL3hKWnWlNFxgRN3YgjenRX9qeDGsG6fLin2i670=
addons:
  browserstack:
    username: treasuredataengi1
    access_key:
      secure: OX2ENqL9Vvpm+mJc9PkW8W3QZzrKwROpx8/9P5iPwbkHWHSnyd4v+Jh0oxm/z6aVgX7OXz5rad15b2qGlDDB1CdYM9eJJR/ppow8C5xh/IDZqijXE0IyidvSEOor9smZefNizj0Ih12F6heBu4Mj0q7Wrj8SB3dKHmRfU//7kOTWIV6cTAxMnmLtvgdXShUX7kxkNykMvyM3ywCea3uCiGMkOgTfwDIPJ0HniCoZ4hPZ74apNn0Gdau+qiwDVDut2scHhW/C7frNKlIaVnaeaRMs0/As+dPfWSwjV1iyMfs3FfeaWOVNv8b2pKvCmIX79xhUEnVX/iRchMu62JfleRHIKOb+xdv0Z/cK14l3jxjWEh9GuNjWdMiKfg3QTaCgKe4lZw9WIqTqFDbc9A8ixGM+uQpgcfosAGjk8laECUTV94VJDl0m4BddWz/mL5qCXi9baba30ir+yhuvYx983g1uo47bVmzMBM1UVcNzZhML5O4v5HCbbHijH92SQe+Bxng3xOssxasemnbyaXDGRrosSBjYS0g0Da7aAPEw6hh9KUHuMGTQ81noJ5tGxqbDPC4kmU51CevxQaWAEklLK4UDl8d4XgNcmse13B7l4+DQdUxIgXboqmI0Bq2tZ2cHPcEeQA2Asrno/93GIKtgtABi1EVwtGAA9fXfJlhvhL0=