dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: Eu9IdOCMDNNtwjs0901xE53zsl6ExoZnGTo+8kOEy4qtZj0/PVCHPEfx3Ty9QFm5mSLVW6BVkJB4gHjZPuSKbMYrKIXwSFZcML4xYXMs7oWh2e9ulOVf8iSH/5MPj8+ib+UPcdwkJLhHXm3lIZs+PhySkIFbA045uPXVRT2Xusw=
  - secure: XCtfTIWdmyjp1ZDH9CPs7eXbOTAhfS031GWsru7rlOqPTWy0/RHL3BI5chBnn7Dh6ig34M6jQ2/4hcP/Qy+nPR9Gx44GF0jhEv3oEF5fyeSu3DsanKew3K0CIbnNRC4lEr/4qMaDkN4yLFeYCYpuvr0v2pyGpP9e+k7j3oqOmM8=
  - secure: o1E51adkfzse6ayaKkf+YPi4xMxDvj6ez1oEsI5HljhVuMbgvOYkrs3dkOSfsORBAR+a9F8bSbrOcXyBDzloj3v1G47r4LaSWFk8QTBDvn8cpAzbx1eErT6FcdzxqmeZ22xWXQhEg17mfomCvULc+ueDToXEP1GGkozp7KZyldk=
  - secure: VuUlF+SdWvjKA0jDLJWcHwaL+H/4shfLhy/1C3HulJVuAOtz7+UQvOsbo2s8tXQic25IynvnBxb366wbDHS4yPEi71oTH/KniV3rYa9jsDM/vIUsHi8X09Scwk8CyD84F7aEL3hKWnWlNFxgRN3YgjenRX9qeDGsG6fLin2i670=
addons:
  browserstack:
    username: yusaku1
    access_key:
      secure: ZxWyNXFz5a3ntk/Z3bSuAzm1dKpTq4XpoAjj9MKlw7Ed4PcFSUWuVR2Ma2OQIY93eVTCsCQ+3OxpQeB7CnA/oZsSSsb1KQhYTi/CqgH77WXhP+T0SB2Jw7+EZc3lD51nviSWnjGwafRoUCPGvHUwJGw7dj+MmTzVyGHLIFhLIWdWsjW+9nYhL1pVvJFwsEWAD6wbUuMYl3usYxRY0Ts6DXOKhpojzF/wBUtkBbmZXmU/qyq3XIxDZkQE93mFiSsdlrJM3jL7RzXxynyct4ZLt4CLc2HkdcGV77/U5Ap2xgW2L0mX0ObisXrcSAnbI3uzDWBfxwSi595MnTDMSBYnJoC47EFC8wo7KQTY931ZvQ0ns8iwunax6qUayIzaxZ3VrJbeajHNqgxkHNexFjMSCStj1CTd3DXBM0ERnFFZuEHSuyb6D+D24NIbUWFOJ7WaUjufz8H13E035zP7yuiuTS+c4YDJ99HatDmiLr+NYVJCS7uvSaTQC7F3yCvI0irirO7rVfn4ccdHeNSDgV6x0F0GxMCVQrufcESJILq9Go2Ct/8wo1kBeszQKA2fAXPfVFzGCqD40bx41Vu0YVGJyJ5y5IWb0mGZvB6luCne1jdPLH56HcjdH0qdOF5zJ51c/jILg3Yaw9afNEkpaBCpUBN+aScBu4NRu7Gp47IihP4=
